name = "Vanilla Reforged"
author = "mystic"
version = "1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a30ec68ff500196b8d4af97f3d7532672120b2f160436d21e2e37b8483a14336"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.131"
