name = "Vanilla Reforged"
author = "mystic"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "793fd6592aea980400693b17078b6a73e680bd0da9fd783f23a545e9148c3489"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.131"
