name = "Vanilla Reforged"
author = "mystic"
version = "1.0.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "efd7f5751e30595f25fb53e5e82b9e1e1a138d7ac04fff1abb84c21a792b68be"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.131"
